#!/usr/bin/env python3
"""Create a public human multi-factor RNA-seq demo dataset.

The dataset is GEO GSE164073: response to SARS-CoV-2 infection in human
cornea, limbus, and sclera cells. It has two useful metadata factors for the
report UI: infection condition and tissue.
"""

from __future__ import annotations

import csv
import gzip
import io
import json
import re
import urllib.request
import zipfile
from pathlib import Path
from xml.sax.saxutils import escape


REPO_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_DIR = REPO_ROOT / "assets/data/gse164073"

COUNT_URL = (
    "https://www.ncbi.nlm.nih.gov/geo/download/"
    "?type=rnaseq_counts&acc=GSE164073&format=file"
    "&file=GSE164073_raw_counts_GRCh38.p13_NCBI.tsv.gz"
)
SOFT_URL = "https://ftp.ncbi.nlm.nih.gov/geo/series/GSE164nnn/GSE164073/soft/GSE164073_family.soft.gz"
GENE_INFO_URL = "https://ftp.ncbi.nlm.nih.gov/gene/DATA/GENE_INFO/Mammalia/Homo_sapiens.gene_info.gz"

QC_HEADERS = [
    "Sample ID",
    "Sample Yield (Mbases)",
    "Percent of (PF) Bases >= Q30",
    "Total Reads (PF)",
    "Total Reads After Trimming",
    "Percent Total Reads after Trimming",
    "Total Mapped Reads (Trimmed)",
    "Percent Total Mapped Reads (Trimmed)",
    "Uniquely Mapped Reads (Trimmed)",
    "Percent Uniquely Mapped Reads (Trimmed)",
    "Percent Non-duplicate Reads (Mapped Trimmed)",
    "PCT_RIBOSOMAL_BASES",
    "PCT_CODING_BASES",
    "PCT_UTR_BASES",
    "PCT_INTRONIC_BASES",
    "PCT_INTERGENIC_BASES",
    "PCT_MRNA_BASES",
    "PCT_CORRECT_STRAND_READS",
    "MEDIAN_5PRIME_TO_3PRIME_BIAS",
]


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    samples = parse_geo_soft(download_gzip_text(SOFT_URL))
    gene_info = parse_gene_info(download_gzip_text(GENE_INFO_URL))
    counts_rows, sample_ids = parse_counts(download_gzip_text(COUNT_URL), gene_info)

    write_csv(OUTPUT_DIR / "counts.csv", counts_rows, ["gene_id", "gene_symbol", "gene_name", *sample_ids])
    write_csv(
        OUTPUT_DIR / "sample_manifest.csv",
        samples,
        ["sample_id", "title", "tissue", "condition", "infection", "time_point", "replicate", "organism"],
    )
    write_qc_workbook(OUTPUT_DIR / "qc_metrics.xlsx", build_demo_qc_rows(samples))
    write_json(OUTPUT_DIR / "samples.json", samples)
    write_json(OUTPUT_DIR / "gene_annotation.json", [
        {
            "gene_id": row["gene_id"],
            "gene_symbol": row["gene_symbol"],
            "description": row["gene_name"],
        }
        for row in counts_rows
        if row["gene_symbol"] or row["gene_name"]
    ])
    write_json(OUTPUT_DIR / "logs/pipeline_provenance.json", {
        "dataset": "GSE164073",
        "title": "Response to SARS-CoV-2 infection in cornea, limbus and sclera from human donors",
        "organism": "Homo sapiens",
        "count_matrix_url": COUNT_URL,
        "metadata_url": SOFT_URL,
        "gene_info_url": GENE_INFO_URL,
        "notes": "Counts were downloaded from NCBI GEO RNA-seq counts and gene symbols were mapped from NCBI Homo_sapiens.gene_info.gz. The QC workbook contains synthetic demo QC values for report UI testing; these QC metrics are not part of the GEO record.",
    })
    write_json(OUTPUT_DIR / "logs/software_versions.json", {
        "demo_builder": Path(__file__).name,
        "count_source": "NCBI GEO RNA-seq counts",
        "gene_annotation_source": "NCBI Gene Homo_sapiens.gene_info.gz",
        "qc_metrics_source": "Synthetic demo QC workbook generated by this script",
    })
    write_readme(OUTPUT_DIR / "README.md", len(counts_rows), len(samples))
    print(f"Wrote {len(counts_rows)} genes and {len(samples)} samples to {OUTPUT_DIR}")


def download_gzip_text(url: str) -> str:
    with urllib.request.urlopen(url, timeout=60) as response:
        compressed = response.read()
    return gzip.decompress(compressed).decode("utf-8", "replace")


def parse_geo_soft(text: str) -> list[dict[str, str]]:
    samples: list[dict[str, str]] = []
    current: dict[str, str] | None = None

    for line in text.splitlines():
        if line.startswith("^SAMPLE = "):
            if current:
                samples.append(normalize_sample(current))
            current = {"sample_id": line.split("=", 1)[1].strip(), "organism": "Homo sapiens"}
            continue

        if current is None:
            continue

        if line.startswith("!Sample_title = "):
            current["title"] = line.split("=", 1)[1].strip()
        elif line.startswith("!Sample_characteristics_ch1 = "):
            value = line.split("=", 1)[1].strip()
            if ":" in value:
                key, raw = value.split(":", 1)
                current[key.strip().replace(" ", "_")] = raw.strip()

    if current:
        samples.append(normalize_sample(current))

    if not samples:
        raise RuntimeError("No samples were parsed from GEO SOFT metadata.")
    return samples


def normalize_sample(sample: dict[str, str]) -> dict[str, str]:
    title = sample.get("title", "")
    infection = sample.get("infection", "")
    condition = "mock" if infection.lower() == "mock" else "sars_cov_2"
    replicate_match = re.search(r"_(\d+)$", title)
    return {
        "sample_id": sample.get("sample_id", ""),
        "title": title,
        "tissue": sample.get("tissue", ""),
        "condition": condition,
        "infection": infection,
        "time_point": sample.get("time_point", ""),
        "replicate": replicate_match.group(1) if replicate_match else "",
        "organism": sample.get("organism", "Homo sapiens"),
    }


def parse_gene_info(text: str) -> dict[str, dict[str, str]]:
    reader = csv.DictReader(io.StringIO(text), delimiter="\t")
    out: dict[str, dict[str, str]] = {}
    for row in reader:
        gene_id = row.get("GeneID", "")
        if not gene_id:
            continue
        out[gene_id] = {
            "gene_symbol": row.get("Symbol", ""),
            "gene_name": row.get("description", ""),
        }
    return out


def parse_counts(text: str, gene_info: dict[str, dict[str, str]]) -> tuple[list[dict[str, str]], list[str]]:
    reader = csv.DictReader(io.StringIO(text), delimiter="\t")
    if not reader.fieldnames or reader.fieldnames[0] != "GeneID":
        raise RuntimeError("Unexpected count matrix header; first column should be GeneID.")

    sample_ids = reader.fieldnames[1:]
    rows: list[dict[str, str]] = []
    for row in reader:
        gene_id = row.get("GeneID", "")
        annotation = gene_info.get(gene_id, {})
        rows.append({
            "gene_id": gene_id,
            "gene_symbol": annotation.get("gene_symbol", ""),
            "gene_name": annotation.get("gene_name", ""),
            **{sample_id: row.get(sample_id, "0") for sample_id in sample_ids},
        })

    if not rows:
        raise RuntimeError("No count rows were parsed.")
    return rows, sample_ids


def build_demo_qc_rows(samples: list[dict[str, str]]) -> list[dict[str, str | int | float]]:
    """Create deterministic, plausible QC metrics for UI testing.

    GSE164073 provides counts and sample metadata, but not the pipeline-level QC
    summary columns used by this report. These rows are intentionally synthetic
    and should only be used as demo/report-fixture data.
    """
    rows: list[dict[str, str | int | float]] = []
    tissue_offsets = {"cornea": 0, "limbus": 420, "sclera": 760}
    for index, sample in enumerate(samples):
        tissue = sample.get("tissue", "")
        condition = sample.get("condition", "")
        replicate = int(sample.get("replicate") or ((index % 3) + 1))
        tissue_offset = tissue_offsets.get(tissue, 240)
        condition_offset = 260 if condition == "sars_cov_2" else 0

        sample_yield = 8200 + tissue_offset + condition_offset + replicate * 310 + (index % 4) * 115
        q30 = 95.15 + (index % 6) * 0.22 - (0.18 if tissue == "sclera" else 0)
        total_reads = round(sample_yield * 1_000_000 / 150)
        trimming_rate = 98.55 + (index % 5) * 0.13 - (0.18 if replicate == 3 else 0)
        reads_after_trimming = round(total_reads * trimming_rate / 100)
        mapping_rate = 96.85 - (0.45 if tissue == "sclera" else 0) + (index % 4) * 0.16
        mapped_reads = round(reads_after_trimming * mapping_rate / 100)
        unique_rate = 90.05 - (0.35 if tissue == "limbus" else 0) + (replicate - 1) * 0.42
        unique_reads = round(mapped_reads * unique_rate / 100)
        nonduplicate_rate = 68.8 + (index % 5) * 1.25 - (0.8 if condition == "sars_cov_2" else 0)
        ribosomal = 1.25 + (index % 4) * 0.32 + (0.25 if tissue == "sclera" else 0)
        coding = 56.6 + (index % 6) * 0.75 - (0.5 if tissue == "limbus" else 0)
        utr = 30.6 + (replicate - 1) * 0.62 + (0.35 if condition == "sars_cov_2" else 0)
        intronic = 4.45 + (index % 5) * 0.28
        intergenic = 1.65 + (index % 3) * 0.2
        mrna = 88.7 + (index % 6) * 0.54
        strand = 94.9 + (index % 5) * 0.27
        bias = 0.94 + (replicate - 1) * 0.045 + (0.025 if tissue == "sclera" else 0)

        rows.append({
            "Sample ID": sample.get("sample_id", ""),
            "Sample Yield (Mbases)": sample_yield,
            "Percent of (PF) Bases >= Q30": round(q30, 2),
            "Total Reads (PF)": total_reads,
            "Total Reads After Trimming": reads_after_trimming,
            "Percent Total Reads after Trimming": round(trimming_rate, 2),
            "Total Mapped Reads (Trimmed)": mapped_reads,
            "Percent Total Mapped Reads (Trimmed)": round(mapping_rate, 2),
            "Uniquely Mapped Reads (Trimmed)": unique_reads,
            "Percent Uniquely Mapped Reads (Trimmed)": round(unique_rate, 2),
            "Percent Non-duplicate Reads (Mapped Trimmed)": round(nonduplicate_rate, 2),
            "PCT_RIBOSOMAL_BASES": round(ribosomal, 2),
            "PCT_CODING_BASES": round(coding, 2),
            "PCT_UTR_BASES": round(utr, 2),
            "PCT_INTRONIC_BASES": round(intronic, 2),
            "PCT_INTERGENIC_BASES": round(intergenic, 2),
            "PCT_MRNA_BASES": round(mrna, 2),
            "PCT_CORRECT_STRAND_READS": round(strand, 2),
            "MEDIAN_5PRIME_TO_3PRIME_BIAS": round(bias, 3),
        })
    return rows


def write_qc_workbook(path: Path, rows: list[dict[str, str | int | float]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    table = [QC_HEADERS, *[[row.get(header, "") for header in QC_HEADERS] for row in rows]]
    sheet_xml = worksheet_xml("Summary", table)
    with zipfile.ZipFile(path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("[Content_Types].xml", content_types_xml())
        archive.writestr("_rels/.rels", root_rels_xml())
        archive.writestr("xl/workbook.xml", workbook_xml("Summary"))
        archive.writestr("xl/_rels/workbook.xml.rels", workbook_rels_xml())
        archive.writestr("xl/worksheets/sheet1.xml", sheet_xml)


def worksheet_xml(sheet_name: str, table: list[list[str | int | float]]) -> str:
    max_col = max((len(row) for row in table), default=1)
    max_row = len(table)
    dimension = f"A1:{column_name(max_col - 1)}{max_row}"
    rows = []
    for row_index, row in enumerate(table, 1):
        cells = []
        for col_index, value in enumerate(row):
            ref = f"{column_name(col_index)}{row_index}"
            cells.append(cell_xml(ref, value))
        rows.append(f'<row r="{row_index}">{"".join(cells)}</row>')

    column_widths = ''.join(
        f'<col min="{index}" max="{index}" width="{width}" customWidth="1"/>'
        for index, width in enumerate([16, 15, 22, 16, 22, 24, 23, 25, 24, 27, 30, 18, 17, 15, 18, 21, 17, 26, 29], 1)
    )
    return f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <dimension ref="{dimension}"/>
  <sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews>
  <cols>{column_widths}</cols>
  <sheetData>{''.join(rows)}</sheetData>
</worksheet>
'''


def cell_xml(ref: str, value: str | int | float) -> str:
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return f'<c r="{ref}"><v>{value}</v></c>'
    return f'<c r="{ref}" t="inlineStr"><is><t>{escape(str(value))}</t></is></c>'


def column_name(index: int) -> str:
    name = ""
    index += 1
    while index:
        index, remainder = divmod(index - 1, 26)
        name = chr(ord("A") + remainder) + name
    return name


def content_types_xml() -> str:
    return '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
  <Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
</Types>
'''


def root_rels_xml() -> str:
    return '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/>
</Relationships>
'''


def workbook_xml(sheet_name: str) -> str:
    return f'''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <sheets><sheet name="{escape(sheet_name)}" sheetId="1" r:id="rId1"/></sheets>
</workbook>
'''


def workbook_rels_xml() -> str:
    return '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/>
</Relationships>
'''


def write_csv(path: Path, rows: list[dict[str, str]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def write_json(path: Path, data) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def write_readme(path: Path, gene_count: int, sample_count: int) -> None:
    path.write_text(
        f"""# GSE164073 Human SARS-CoV-2 Ocular Surface Demo

This folder contains a public human bulk RNA-seq demo dataset for the report app.

- GEO accession: GSE164073
- Organism: Homo sapiens
- Samples: {sample_count}
- Genes: {gene_count}
- Primary DE factor: `condition` (`sars_cov_2` vs `mock`)
- Useful blocking/covariate factor: `tissue` (`cornea`, `limbus`, `sclera`)

Source files:

- Counts: {COUNT_URL}
- Metadata: {SOFT_URL}
- Gene symbols: {GENE_INFO_URL}
- QC metrics: synthetic demo workbook in `qc_metrics.xlsx`, generated for report UI testing only.

Regenerate this fixture with:

```bash
python3 scripts/download_gse164073_demo.py
python3 scripts/validate_assets.py assets/data/gse164073
```

Build a single-file demo report with:

```bash
python3 scripts/build_report_bundle.py --data-root assets/data/gse164073 --output dist/gse164073-report.html
```
""",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
